#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

require_once __DIR__.'/vendor/autoload.php';

Application::configure(basePath: __DIR__)
    ->withRouting(
        web: __DIR__.'/routes/web.php',
        api: __DIR__.'/routes/api.php',
    )
    ->withMiddleware(function () {
        // middleware 定義（任意）
    })
    ->withExceptions(function () {
        // 例外ハンドラ定義（任意）
    })
    ->create(); 
